"""Optional plotting utilities for IFcalc.

This module is intentionally separated from core calculation logic so that
environments without matplotlib can still import and use `IFcalc`.
"""

from __future__ import annotations

import csv
from pathlib import Path


def _to_display_title(raw_name: str) -> str:
    """Convert raw journal name to title-style text for plotting.

    Args:
        raw_name: Raw journal name string.

    Returns:
        Name with each word capitalized.
    """

    normalized: str = raw_name.replace("_", " ").replace("-", " ").strip()
    return " ".join(word.capitalize() for word in normalized.split())


def _load_if_csv(csv_path: Path) -> tuple[list[int], list[tuple[str, list[float]]]]:
    """Load IF table exported by `write()` from CSV.

    Args:
        csv_path: Path to CSV file generated by `write(...)`.

    Returns:
        A tuple of:
        - year list (x-axis)
        - series list where each item is `(delta_label, if_values)`

    Raises:
        ValueError: If CSV format is invalid.
    """

    with csv_path.open("r", encoding="utf-8", newline="") as fp:
        reader = csv.reader(fp)
        rows: list[list[str]] = list(reader)

    if len(rows) < 2:
        raise ValueError("CSV must contain header and at least one data row.")

    header: list[str] = rows[0]
    if not header or header[0] != "delta":
        raise ValueError("Invalid CSV header: first column must be 'delta'.")
    if len(header) < 2:
        raise ValueError("Invalid CSV header: missing year columns.")

    years: list[int] = []
    for raw_year in header[1:]:
        try:
            years.append(int(raw_year))
        except ValueError as exc:
            raise ValueError(f"Invalid year column: {raw_year!r}") from exc

    series: list[tuple[str, list[float]]] = []
    year_count: int = len(years)
    for row in rows[1:]:
        if len(row) != year_count + 1:
            raise ValueError("Data row column count does not match header.")

        delta_label: str = row[0]
        values: list[float] = []
        for raw_value in row[1:]:
            try:
                values.append(float(raw_value))
            except ValueError as exc:
                raise ValueError(f"Invalid IF value: {raw_value!r}") from exc
        series.append((delta_label, values))

    return years, series


def plot_from_csv(csv_path: str | Path, output_path: str | Path | None = None) -> Path:
    """Draw IF curves directly from CSV exported by `write(...)`.

    The plot uses:
    - x-axis: year columns in CSV
    - y-axis: IF values
    - one line per delta row

    Args:
        csv_path: Source CSV path from `write(...)`.
        output_path: Optional output image path.
            If omitted, output will be `<csv_stem>.png` in the same directory.

    Returns:
        Absolute path to the saved figure image.

    Raises:
        FileNotFoundError: If input CSV does not exist.
        ImportError: If matplotlib is unavailable in current environment.
        ValueError: If CSV format is invalid.

    Examples:
        >>> image_path = plot_from_csv("chinese physics c.csv")
        >>> image_path.suffix
        '.png'
    """

    path: Path = Path(csv_path)
    if not path.exists():
        raise FileNotFoundError(f"CSV file not found: {path}")

    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise ImportError(
            "matplotlib is required for plotting. "
            "Install it in your current environment first."
        ) from exc

    years, series = _load_if_csv(path)
    title_text: str = _to_display_title(path.stem)

    figure = plt.figure(figsize=(8, 5), dpi=120)
    for delta_label, values in series:
        legend_label: str = delta_label if delta_label.endswith("%") else f"{delta_label}%"
        plt.plot(years, values, marker="o", linewidth=1.6, label=legend_label)

    plt.xlabel("Year")
    plt.ylabel("IF")
    plt.title(title_text)
    plt.xticks(years)
    plt.grid(True, linestyle="--", linewidth=0.5, alpha=0.5)
    plt.legend()
    plt.tight_layout()

    target_path: Path = Path(output_path) if output_path is not None else path.with_suffix(".png")
    figure.savefig(target_path)
    plt.close(figure)

    return target_path.resolve()


def plot_analysis_from_csv(csv_path: str | Path, output_path: str | Path | None = None) -> Path:
    """Draw mean/std relationship against delta from analysis CSV.

    Expected CSV format (from `write(..., analyse=True)`):
    - columns: `delta,mean,std[,rsd]`

    Plot contents:
    - solid line: `mean` vs `delta`
    - dashed lines: `mean + std` and `mean - std`
    - shaded area: between upper/lower dashed lines in semi-transparent red

    Args:
        csv_path: Source analysis CSV path.
        output_path: Optional output image path.
            If omitted, output will be `<csv_stem>.png` in the same directory.

    Returns:
        Absolute path to the saved figure image.

    Raises:
        FileNotFoundError: If input CSV does not exist.
        ImportError: If matplotlib is unavailable in current environment.
        ValueError: If CSV format is invalid.
    """

    path: Path = Path(csv_path)
    if not path.exists():
        raise FileNotFoundError(f"CSV file not found: {path}")

    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise ImportError(
            "matplotlib is required for plotting. "
            "Install it in your current environment first."
        ) from exc

    with path.open("r", encoding="utf-8", newline="") as fp:
        reader = csv.reader(fp)
        rows: list[list[str]] = list(reader)

    if len(rows) < 2:
        raise ValueError("Analysis CSV must contain header and at least one data row.")

    header: list[str] = rows[0]
    if len(header) < 3 or header[0] != "delta" or header[1] != "mean" or header[2] != "std":
        raise ValueError("Analysis CSV header must start with: delta,mean,std")

    deltas: list[float] = []
    means: list[float] = []
    stds: list[float] = []
    for row in rows[1:]:
        if len(row) < 3:
            raise ValueError("Analysis CSV row must contain at least 3 columns.")
        try:
            deltas.append(float(row[0]))
            means.append(float(row[1]))
            stds.append(float(row[2]))
        except ValueError as exc:
            raise ValueError(f"Invalid numeric value in analysis CSV row: {row!r}") from exc

    upper: list[float] = [mean + std for mean, std in zip(means, stds, strict=True)]
    lower: list[float] = [mean - std for mean, std in zip(means, stds, strict=True)]

    title_text: str = _to_display_title(path.stem)

    figure = plt.figure(figsize=(8, 5), dpi=120)
    plt.plot(deltas, means, color="tab:blue", linewidth=1.8)
    plt.plot(deltas, upper, color="tab:red", linestyle="--", linewidth=1.3)
    plt.plot(deltas, lower, color="tab:red", linestyle="--", linewidth=1.3)
    plt.fill_between(deltas, lower, upper, color="red", alpha=0.2)

    plt.xlabel("Delta")
    plt.ylabel("IF")
    plt.title(title_text)
    plt.xticks(deltas)
    plt.grid(True, linestyle="--", linewidth=0.5, alpha=0.5)
    plt.tight_layout()

    target_path: Path = Path(output_path) if output_path is not None else path.with_suffix(".png")
    figure.savefig(target_path)
    plt.close(figure)

    return target_path.resolve()


def plot_decrease_from_csv(csv_path: str | Path, output_path: str | Path | None = None) -> Path:
    """Draw decrease-percentage curves from `analyse(...)` output CSV.

    Expected CSV format:
    - header: `year,<delta1>,<delta2>,...`
    - rows: `<year>,<decrease_for_delta1>,<decrease_for_delta2>,...`

    Plot settings:
    - x-axis: year
    - y-axis: decrease percentage
    - one curve per delta column
    - legend labels are formatted as percentages, such as `10%`
    - title is based on journal name parsed from file stem

    Args:
        csv_path: Source decrease CSV path.
        output_path: Optional output image path.
            If omitted, output will be `<csv_stem>.png` in the same directory.

    Returns:
        Absolute path to the saved figure image.

    Raises:
        FileNotFoundError: If input CSV does not exist.
        ImportError: If matplotlib is unavailable in current environment.
        ValueError: If CSV format is invalid.
    """

    path: Path = Path(csv_path)
    if not path.exists():
        raise FileNotFoundError(f"CSV file not found: {path}")

    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise ImportError(
            "matplotlib is required for plotting. "
            "Install it in your current environment first."
        ) from exc

    with path.open("r", encoding="utf-8", newline="") as fp:
        reader = csv.reader(fp)
        rows: list[list[str]] = list(reader)

    if len(rows) < 2:
        raise ValueError("Decrease CSV must contain header and at least one data row.")

    header: list[str] = rows[0]
    if len(header) < 2 or header[0] != "year":
        raise ValueError("Decrease CSV header must be: year,<delta1>,<delta2>,...")

    delta_labels: list[str] = header[1:]
    years: list[int] = []
    value_matrix: list[list[float]] = []
    for row in rows[1:]:
        if len(row) < len(delta_labels) + 1:
            raise ValueError("Decrease CSV row column count does not match header.")
        try:
            years.append(int(row[0]))
        except ValueError as exc:
            raise ValueError(f"Invalid year value: {row[0]!r}") from exc

        values: list[float] = []
        for raw_value in row[1 : len(delta_labels) + 1]:
            try:
                values.append(float(raw_value))
            except ValueError as exc:
                raise ValueError(f"Invalid decrease value: {raw_value!r}") from exc
        value_matrix.append(values)

    # value_matrix shape: [year_index][delta_index] -> plot by delta
    title_stem: str = path.stem
    if title_stem.endswith("_decrease"):
        title_stem = title_stem[: -len("_decrease")]
    title_text: str = _to_display_title(title_stem)

    figure = plt.figure(figsize=(8, 5), dpi=120)
    for delta_index, delta_label in enumerate(delta_labels):
        try:
            if float(delta_label) == 0.0:
                continue
        except ValueError:
            pass

        series_values: list[float] = [row[delta_index] for row in value_matrix]
        legend_label: str = delta_label if delta_label.endswith("%") else f"{delta_label}%"
        plt.plot(years, series_values, marker="o", linewidth=1.4, label=legend_label)

    plt.xlabel("Year")
    plt.ylabel("Decrease (%)")
    plt.title(title_text)
    plt.xticks(years)
    plt.grid(True, linestyle="--", linewidth=0.5, alpha=0.5)
    plt.legend()
    plt.tight_layout()

    target_path: Path = Path(output_path) if output_path is not None else path.with_suffix(".png")
    figure.savefig(target_path)
    plt.close(figure)

    return target_path.resolve()
